<?php
	return array(
		'ad' => array('label'=>'Andorra', 'data-imagecss'=>'flag ad', 'value'=>'ad'),
		'ae' => array('label'=>'United Arab Emirates', 'data-imagecss'=>'flag ae', 'value'=>'ae'),
		'af' => array('label'=>'Afghanistan', 'data-imagecss'=>'flag af', 'value'=>'af'),
		'ag' => array('label'=>'Antigua and Barbuda', 'data-imagecss'=>'flag ag', 'value'=>'ag'),
		'ai' => array('label'=>'Anguilla', 'data-imagecss'=>'flag ai', 'value'=>'ai'),
		'al' => array('label'=>'Albania', 'data-imagecss'=>'flag al', 'value'=>'al'),
		'am' => array('label'=>'Armenia', 'data-imagecss'=>'flag am', 'value'=>'am'),
		'an' => array('label'=>'Netherlands Antilles', 'data-imagecss'=>'flag an', 'value'=>'an'),
		'ao' => array('label'=>'Angola', 'data-imagecss'=>'flag ao', 'value'=>'ao'),
		'aq' => array('label'=>'Antarctica', 'data-imagecss'=>'flag aq', 'value'=>'aq'),
		'ar' => array('label'=>'Argentina', 'data-imagecss'=>'flag ar', 'value'=>'ar'),
		'as' => array('label'=>'American Samoa', 'data-imagecss'=>'flag as', 'value'=>'as'),
		'at' => array('label'=>'Austria', 'data-imagecss'=>'flag at', 'value'=>'at'),
		'au' => array('label'=>'Australia', 'data-imagecss'=>'flag au', 'value'=>'au'),
		'aw' => array('label'=>'Aruba', 'data-imagecss'=>'flag aw', 'value'=>'aw'),
		'ax' => array('label'=>'Aland Islands', 'data-imagecss'=>'flag ax', 'value'=>'ax'),
		'az' => array('label'=>'Azerbaijan', 'data-imagecss'=>'flag az', 'value'=>'az'),
		'ba' => array('label'=>'Bosnia and Herzegovina', 'data-imagecss'=>'flag ba', 'value'=>'ba'),
		'bb' => array('label'=>'Barbados', 'data-imagecss'=>'flag bb', 'value'=>'bb'),
		'bd' => array('label'=>'Bangladesh', 'data-imagecss'=>'flag bd', 'value'=>'bd'),
		'be' => array('label'=>'Belgium', 'data-imagecss'=>'flag be', 'value'=>'be'),
		'bf' => array('label'=>'Burkina Faso', 'data-imagecss'=>'flag bf', 'value'=>'bf'),
		'bg' => array('label'=>'Bulgaria', 'data-imagecss'=>'flag bg', 'value'=>'bg'),
		'bh' => array('label'=>'Bahrain', 'data-imagecss'=>'flag bh', 'value'=>'bh'),
		'bi' => array('label'=>'Burundi', 'data-imagecss'=>'flag bi', 'value'=>'bi'),
		'bj' => array('label'=>'Benin', 'data-imagecss'=>'flag bj', 'value'=>'bj'),
		'bm' => array('label'=>'Bermuda', 'data-imagecss'=>'flag bm', 'value'=>'bm'),
		'bn' => array('label'=>'Brunei Darussalam', 'data-imagecss'=>'flag bn', 'value'=>'bn'),
		'bo' => array('label'=>'Bolivia', 'data-imagecss'=>'flag bo', 'value'=>'bo'),
		'br' => array('label'=>'Brazil', 'data-imagecss'=>'flag br', 'value'=>'br'),
		'bs' => array('label'=>'Bahamas', 'data-imagecss'=>'flag bs', 'value'=>'bs'),
		'bt' => array('label'=>'Bhutan', 'data-imagecss'=>'flag bt', 'value'=>'bt'),
		'bv' => array('label'=>'Bouvet Island', 'data-imagecss'=>'flag bv', 'value'=>'bv'),
		'bw' => array('label'=>'Botswana', 'data-imagecss'=>'flag bw', 'value'=>'bw'),
		'by' => array('label'=>'Belarus', 'data-imagecss'=>'flag by', 'value'=>'by'),
		'bz' => array('label'=>'Belize', 'data-imagecss'=>'flag bz', 'value'=>'bz'),
		'ca' => array('label'=>'Canada', 'data-imagecss'=>'flag ca', 'value'=>'ca'),
		'cc' => array('label'=>'Cocos (Keeling) Islands', 'data-imagecss'=>'flag cc', 'value'=>'cc'),
		'cd' => array('label'=>'Democratic Republic of the Congo', 'data-imagecss'=>'flag cd', 'value'=>'cd'),
		'cf' => array('label'=>'Central African Republic', 'data-imagecss'=>'flag cf', 'value'=>'cf'),
		'cg' => array('label'=>'Congo', 'data-imagecss'=>'flag cg', 'value'=>'cg'),
		'ch' => array('label'=>'Switzerland', 'data-imagecss'=>'flag ch', 'value'=>'ch'),
		'ci' => array('label'=>'Cote D\'Ivoire (Ivory Coast)', 'data-imagecss'=>'flag ci', 'value'=>'ci'),
		'ck' => array('label'=>'Cook Islands', 'data-imagecss'=>'flag ck', 'value'=>'ck'),
		'cl' => array('label'=>'Chile', 'data-imagecss'=>'flag cl', 'value'=>'cl'),
		'cm' => array('label'=>'Cameroon', 'data-imagecss'=>'flag cm', 'value'=>'cm'),
		'cn' => array('label'=>'China', 'data-imagecss'=>'flag cn', 'value'=>'cn'),
		'co' => array('label'=>'Colombia', 'data-imagecss'=>'flag co', 'value'=>'co'),
		'cr' => array('label'=>'Costa Rica', 'data-imagecss'=>'flag cr', 'value'=>'cr'),
		'cs' => array('label'=>'Serbia and Montenegro', 'data-imagecss'=>'flag cs', 'value'=>'cs'),
		'cu' => array('label'=>'Cuba', 'data-imagecss'=>'flag cu', 'value'=>'cu'),
		'cv' => array('label'=>'Cape Verde', 'data-imagecss'=>'flag cv', 'value'=>'cv'),
		'cx' => array('label'=>'Christmas Island', 'data-imagecss'=>'flag cx', 'value'=>'cx'),
		'cy' => array('label'=>'Cyprus', 'data-imagecss'=>'flag cy', 'value'=>'cy'),
		'cz' => array('label'=>'Czech Republic', 'data-imagecss'=>'flag cz', 'value'=>'cz'),
		'de' => array('label'=>'Germany', 'data-imagecss'=>'flag de', 'value'=>'de'),
		'dj' => array('label'=>'Djibouti', 'data-imagecss'=>'flag dj', 'value'=>'dj'),
		'dk' => array('label'=>'Denmark', 'data-imagecss'=>'flag dk', 'value'=>'dk'),
		'dm' => array('label'=>'Dominica', 'data-imagecss'=>'flag dm', 'value'=>'dm'),
		'do' => array('label'=>'Dominican Republic', 'data-imagecss'=>'flag do', 'value'=>'do'),
		'dz' => array('label'=>'Algeria', 'data-imagecss'=>'flag dz', 'value'=>'dz'),
		'ec' => array('label'=>'Ecuador', 'data-imagecss'=>'flag ec', 'value'=>'ec'),
		'ee' => array('label'=>'Estonia', 'data-imagecss'=>'flag ee', 'value'=>'ee'),
		'eg' => array('label'=>'Egypt', 'data-imagecss'=>'flag eg', 'value'=>'eg'),
		'eh' => array('label'=>'Western Sahara', 'data-imagecss'=>'flag eh', 'value'=>'eh'),
		'er' => array('label'=>'Eritrea', 'data-imagecss'=>'flag er', 'value'=>'er'),
		'es' => array('label'=>'Spain', 'data-imagecss'=>'flag es', 'value'=>'es'),
		'et' => array('label'=>'Ethiopia', 'data-imagecss'=>'flag et', 'value'=>'et'),
		'fi' => array('label'=>'Finland', 'data-imagecss'=>'flag fi', 'value'=>'fi'),
		'fj' => array('label'=>'Fiji', 'data-imagecss'=>'flag fj', 'value'=>'fj'),
		'fk' => array('label'=>'Falkland Islands (Malvinas)', 'data-imagecss'=>'flag fk', 'value'=>'fk'),
		'fm' => array('label'=>'Federated States of Micronesia', 'data-imagecss'=>'flag fm', 'value'=>'fm'),
		'fo' => array('label'=>'Faroe Islands', 'data-imagecss'=>'flag fo', 'value'=>'fo'),
		'fr' => array('label'=>'France', 'data-imagecss'=>'flag fr', 'value'=>'fr'),
		'fx' => array('label'=>'France, Metropolitan', 'data-imagecss'=>'flag fx', 'value'=>'fx'),
		'ga' => array('label'=>'Gabon', 'data-imagecss'=>'flag ga', 'value'=>'ga'),
		'gb' => array('label'=>'Great Britain (UK)', 'data-imagecss'=>'flag gb', 'value'=>'gb'),
		'gd' => array('label'=>'Grenada', 'data-imagecss'=>'flag gd', 'value'=>'gd'),
		'ge' => array('label'=>'Georgia', 'data-imagecss'=>'flag ge', 'value'=>'ge'),
		'gf' => array('label'=>'French Guiana', 'data-imagecss'=>'flag gf', 'value'=>'gf'),
		'gh' => array('label'=>'Ghana', 'data-imagecss'=>'flag gh', 'value'=>'gh'),
		'gi' => array('label'=>'Gibraltar', 'data-imagecss'=>'flag gi', 'value'=>'gi'),
		'gl' => array('label'=>'Greenland', 'data-imagecss'=>'flag gl', 'value'=>'gl'),
		'gm' => array('label'=>'Gambia', 'data-imagecss'=>'flag gm', 'value'=>'gm'),
		'gn' => array('label'=>'Guinea', 'data-imagecss'=>'flag gn', 'value'=>'gn'),
		'gp' => array('label'=>'Guadeloupe', 'data-imagecss'=>'flag gp', 'value'=>'gp'),
		'gq' => array('label'=>'Equatorial Guinea', 'data-imagecss'=>'flag gq', 'value'=>'gq'),
		'gr' => array('label'=>'Greece', 'data-imagecss'=>'flag gr', 'value'=>'gr'),
		'gs' => array('label'=>'S. Georgia and S. Sandwich Islands', 'data-imagecss'=>'flag gs', 'value'=>'gs'),
		'gt' => array('label'=>'Guatemala', 'data-imagecss'=>'flag gt', 'value'=>'gt'),
		'gu' => array('label'=>'Guam', 'data-imagecss'=>'flag gu', 'value'=>'gu'),
		'gw' => array('label'=>'Guinea-Bissau', 'data-imagecss'=>'flag gw', 'value'=>'gw'),
		'gy' => array('label'=>'Guyana', 'data-imagecss'=>'flag gy', 'value'=>'gy'),
		'hk' => array('label'=>'Hong Kong', 'data-imagecss'=>'flag hk', 'value'=>'hk'),
		'hm' => array('label'=>'Heard Island and McDonald Islands', 'data-imagecss'=>'flag hm', 'value'=>'hm'),
		'hn' => array('label'=>'Honduras', 'data-imagecss'=>'flag hn', 'value'=>'hn'),
		'hr' => array('label'=>'Croatia (Hrvatska)', 'data-imagecss'=>'flag hr', 'value'=>'hr'),
		'ht' => array('label'=>'Haiti', 'data-imagecss'=>'flag ht', 'value'=>'ht'),
		'hu' => array('label'=>'Hungary', 'data-imagecss'=>'flag hu', 'value'=>'hu'),
		'id' => array('label'=>'Indonesia', 'data-imagecss'=>'flag id', 'value'=>'id'),
		'ie' => array('label'=>'Ireland', 'data-imagecss'=>'flag ie', 'value'=>'ie'),
		'il' => array('label'=>'Israel', 'data-imagecss'=>'flag il', 'value'=>'il'),
		'in' => array('label'=>'India', 'data-imagecss'=>'flag in', 'value'=>'in'),
		'io' => array('label'=>'British Indian Ocean Territory', 'data-imagecss'=>'flag io', 'value'=>'io'),
		'iq' => array('label'=>'Iraq', 'data-imagecss'=>'flag iq', 'value'=>'iq'),
		'ir' => array('label'=>'Iran', 'data-imagecss'=>'flag ir', 'value'=>'ir'),
		'is' => array('label'=>'Iceland', 'data-imagecss'=>'flag is', 'value'=>'is'),
		'it' => array('label'=>'Italy', 'data-imagecss'=>'flag it', 'value'=>'it'),
		'jm' => array('label'=>'Jamaica', 'data-imagecss'=>'flag jm', 'value'=>'jm'),
		'jo' => array('label'=>'Jordan', 'data-imagecss'=>'flag jo', 'value'=>'jo'),
		'jp' => array('label'=>'Japan', 'data-imagecss'=>'flag jp', 'value'=>'jp'),
		'ke' => array('label'=>'Kenya', 'data-imagecss'=>'flag ke', 'value'=>'ke'),
		'kg' => array('label'=>'Kyrgyzstan', 'data-imagecss'=>'flag kg', 'value'=>'kg'),
		'kh' => array('label'=>'Cambodia', 'data-imagecss'=>'flag kh', 'value'=>'kh'),
		'ki' => array('label'=>'Kiribati', 'data-imagecss'=>'flag ki', 'value'=>'ki'),
		'km' => array('label'=>'Comoros', 'data-imagecss'=>'flag km', 'value'=>'km'),
		'kn' => array('label'=>'Saint Kitts and Nevis', 'data-imagecss'=>'flag kn', 'value'=>'kn'),
		'kp' => array('label'=>'Korea (North)', 'data-imagecss'=>'flag kp', 'value'=>'kp'),
		'kr' => array('label'=>'Korea (South)', 'data-imagecss'=>'flag kr', 'value'=>'kr'),
		'kw' => array('label'=>'Kuwait', 'data-imagecss'=>'flag kw', 'value'=>'kw'),
		'ky' => array('label'=>'Cayman Islands', 'data-imagecss'=>'flag ky', 'value'=>'ky'),
		'kz' => array('label'=>'Kazakhstan', 'data-imagecss'=>'flag kz', 'value'=>'kz'),
		'la' => array('label'=>'Laos', 'data-imagecss'=>'flag la', 'value'=>'la'),
		'lb' => array('label'=>'Lebanon', 'data-imagecss'=>'flag lb', 'value'=>'lb'),
		'lc' => array('label'=>'Saint Lucia', 'data-imagecss'=>'flag lc', 'value'=>'lc'),
		'li' => array('label'=>'Liechtenstein', 'data-imagecss'=>'flag li', 'value'=>'li'),
		'lk' => array('label'=>'Sri Lanka', 'data-imagecss'=>'flag lk', 'value'=>'lk'),
		'lr' => array('label'=>'Liberia', 'data-imagecss'=>'flag lr', 'value'=>'lr'),
		'ls' => array('label'=>'Lesotho', 'data-imagecss'=>'flag ls', 'value'=>'ls'),
		'lt' => array('label'=>'Lithuania', 'data-imagecss'=>'flag lt', 'value'=>'lt'),
		'lu' => array('label'=>'Luxembourg', 'data-imagecss'=>'flag lu', 'value'=>'lu'),
		'lv' => array('label'=>'Latvia', 'data-imagecss'=>'flag lv', 'value'=>'lv'),
		'ly' => array('label'=>'Libya', 'data-imagecss'=>'flag ly', 'value'=>'ly'),
		'ma' => array('label'=>'Morocco', 'data-imagecss'=>'flag ma', 'value'=>'ma'),
		'mc' => array('label'=>'Monaco', 'data-imagecss'=>'flag mc', 'value'=>'mc'),
		'md' => array('label'=>'Moldova', 'data-imagecss'=>'flag md', 'value'=>'md'),
		'mg' => array('label'=>'Madagascar', 'data-imagecss'=>'flag mg', 'value'=>'mg'),
		'mh' => array('label'=>'Marshall Islands', 'data-imagecss'=>'flag mh', 'value'=>'mh'),
		'mk' => array('label'=>'Macedonia', 'data-imagecss'=>'flag mk', 'value'=>'mk'),
		'ml' => array('label'=>'Mali', 'data-imagecss'=>'flag ml', 'value'=>'ml'),
		'mm' => array('label'=>'Myanmar', 'data-imagecss'=>'flag mm', 'value'=>'mm'),
		'mn' => array('label'=>'Mongolia', 'data-imagecss'=>'flag mn', 'value'=>'mn'),
		'mo' => array('label'=>'Macao', 'data-imagecss'=>'flag mo', 'value'=>'mo'),
		'mp' => array('label'=>'Northern Mariana Islands', 'data-imagecss'=>'flag mp', 'value'=>'mp'),
		'mq' => array('label'=>'Martinique', 'data-imagecss'=>'flag mq', 'value'=>'mq'),
		'mr' => array('label'=>'Mauritania', 'data-imagecss'=>'flag mr', 'value'=>'mr'),
		'ms' => array('label'=>'Montserrat', 'data-imagecss'=>'flag ms', 'value'=>'ms'),
		'mt' => array('label'=>'Malta', 'data-imagecss'=>'flag mt', 'value'=>'mt'),
		'mu' => array('label'=>'Mauritius', 'data-imagecss'=>'flag mu', 'value'=>'mu'),
		'mv' => array('label'=>'Maldives', 'data-imagecss'=>'flag mv', 'value'=>'mv'),
		'mw' => array('label'=>'Malawi', 'data-imagecss'=>'flag mw', 'value'=>'mw'),
		'mx' => array('label'=>'Mexico', 'data-imagecss'=>'flag mx', 'value'=>'mx'),
		'my' => array('label'=>'Malaysia', 'data-imagecss'=>'flag my', 'value'=>'my'),
		'mz' => array('label'=>'Mozambique', 'data-imagecss'=>'flag mz', 'value'=>'mz'),
		'na' => array('label'=>'Namibia', 'data-imagecss'=>'flag na', 'value'=>'na'),
		'nc' => array('label'=>'New Caledonia', 'data-imagecss'=>'flag nc', 'value'=>'nc'),
		'ne' => array('label'=>'Niger', 'data-imagecss'=>'flag ne', 'value'=>'ne'),
		'nf' => array('label'=>'Norfolk Island', 'data-imagecss'=>'flag nf', 'value'=>'nf'),
		'ng' => array('label'=>'Nigeria', 'data-imagecss'=>'flag ng', 'value'=>'ng'),
		'ni' => array('label'=>'Nicaragua', 'data-imagecss'=>'flag ni', 'value'=>'ni'),
		'nl' => array('label'=>'Netherlands', 'data-imagecss'=>'flag nl', 'value'=>'nl'),
		'no' => array('label'=>'Norway', 'data-imagecss'=>'flag no', 'value'=>'no'),
		'np' => array('label'=>'Nepal', 'data-imagecss'=>'flag np', 'value'=>'np'),
		'nr' => array('label'=>'Nauru', 'data-imagecss'=>'flag nr', 'value'=>'nr'),
		'nu' => array('label'=>'Niue', 'data-imagecss'=>'flag nu', 'value'=>'nu'),
		'nz' => array('label'=>'New Zealand (Aotearoa)', 'data-imagecss'=>'flag nz', 'value'=>'nz'),
		'om' => array('label'=>'Oman', 'data-imagecss'=>'flag om', 'value'=>'om'),
		'pa' => array('label'=>'Panama', 'data-imagecss'=>'flag pa', 'value'=>'pa'),
		'pe' => array('label'=>'Peru', 'data-imagecss'=>'flag pe', 'value'=>'pe'),
		'pf' => array('label'=>'French Polynesia', 'data-imagecss'=>'flag pf', 'value'=>'pf'),
		'pg' => array('label'=>'Papua New Guinea', 'data-imagecss'=>'flag pg', 'value'=>'pg'),
		'ph' => array('label'=>'Philippines', 'data-imagecss'=>'flag ph', 'value'=>'ph'),
		'pk' => array('label'=>'Pakistan', 'data-imagecss'=>'flag pk', 'value'=>'pk'),
		'pl' => array('label'=>'Poland', 'data-imagecss'=>'flag pl', 'value'=>'pl'),
		'pm' => array('label'=>'Saint Pierre and Miquelon', 'data-imagecss'=>'flag pm', 'value'=>'pm'),
		'pn' => array('label'=>'Pitcairn', 'data-imagecss'=>'flag pn', 'value'=>'pn'),
		'pr' => array('label'=>'Puerto Rico', 'data-imagecss'=>'flag pr', 'value'=>'pr'),
		'ps' => array('label'=>'Palestinian Territory', 'data-imagecss'=>'flag ps', 'value'=>'ps'),
		'pt' => array('label'=>'Portugal', 'data-imagecss'=>'flag pt', 'value'=>'pt'),
		'pw' => array('label'=>'Palau', 'data-imagecss'=>'flag pw', 'value'=>'pw'),
		'py' => array('label'=>'Paraguay', 'data-imagecss'=>'flag py', 'value'=>'py'),
		'qa' => array('label'=>'Qatar', 'data-imagecss'=>'flag qa', 'value'=>'qa'),
		're' => array('label'=>'Reunion', 'data-imagecss'=>'flag re', 'value'=>'re'),
		'ro' => array('label'=>'Romania', 'data-imagecss'=>'flag ro', 'value'=>'ro'),
		'ru' => array('label'=>'Russian Federation', 'data-imagecss'=>'flag ru', 'value'=>'ru'),
		'rw' => array('label'=>'Rwanda', 'data-imagecss'=>'flag rw', 'value'=>'rw'),
		'sa' => array('label'=>'Saudi Arabia', 'data-imagecss'=>'flag sa', 'value'=>'sa'),
		'sb' => array('label'=>'Solomon Islands', 'data-imagecss'=>'flag sb', 'value'=>'sb'),
		'sc' => array('label'=>'Seychelles', 'data-imagecss'=>'flag sc', 'value'=>'sc'),
		'sd' => array('label'=>'Sudan', 'data-imagecss'=>'flag sd', 'value'=>'sd'),
		'se' => array('label'=>'Sweden', 'data-imagecss'=>'flag se', 'value'=>'se'),
		'sg' => array('label'=>'Singapore', 'data-imagecss'=>'flag sg', 'value'=>'sg'),
		'sh' => array('label'=>'Saint Helena', 'data-imagecss'=>'flag sh', 'value'=>'sh'),
		'si' => array('label'=>'Slovenia', 'data-imagecss'=>'flag si', 'value'=>'si'),
		'sj' => array('label'=>'Svalbard and Jan Mayen', 'data-imagecss'=>'flag sj', 'value'=>'sj'),
		'sk' => array('label'=>'Slovakia', 'data-imagecss'=>'flag sk', 'value'=>'sk'),
		'sl' => array('label'=>'Sierra Leone', 'data-imagecss'=>'flag sl', 'value'=>'sl'),
		'sm' => array('label'=>'San Marino', 'data-imagecss'=>'flag sm', 'value'=>'sm'),
		'sn' => array('label'=>'Senegal', 'data-imagecss'=>'flag sn', 'value'=>'sn'),
		'so' => array('label'=>'Somalia', 'data-imagecss'=>'flag so', 'value'=>'so'),
		'sr' => array('label'=>'Suriname', 'data-imagecss'=>'flag sr', 'value'=>'sr'),
		'st' => array('label'=>'Sao Tome and Principe', 'data-imagecss'=>'flag st', 'value'=>'st'),
		'su' => array('label'=>'USSR (former)', 'data-imagecss'=>'flag su', 'value'=>'su'),
		'sv' => array('label'=>'El Salvador', 'data-imagecss'=>'flag sv', 'value'=>'sv'),
		'sy' => array('label'=>'Syria', 'data-imagecss'=>'flag sy', 'value'=>'sy'),
		'sz' => array('label'=>'Swaziland', 'data-imagecss'=>'flag sz', 'value'=>'sz'),
		'tc' => array('label'=>'Turks and Caicos Islands', 'data-imagecss'=>'flag tc', 'value'=>'tc'),
		'td' => array('label'=>'Chad', 'data-imagecss'=>'flag td', 'value'=>'td'),
		'tf' => array('label'=>'French Southern Territories', 'data-imagecss'=>'flag tf', 'value'=>'tf'),
		'tg' => array('label'=>'Togo', 'data-imagecss'=>'flag tg', 'value'=>'tg'),
		'th' => array('label'=>'Thailand', 'data-imagecss'=>'flag th', 'value'=>'th'),
		'tj' => array('label'=>'Tajikistan', 'data-imagecss'=>'flag tj', 'value'=>'tj'),
		'tk' => array('label'=>'Tokelau', 'data-imagecss'=>'flag tk', 'value'=>'tk'),
		'tl' => array('label'=>'Timor-Leste', 'data-imagecss'=>'flag tl', 'value'=>'tl'),
		'tm' => array('label'=>'Turkmenistan', 'data-imagecss'=>'flag tm', 'value'=>'tm'),
		'tn' => array('label'=>'Tunisia', 'data-imagecss'=>'flag tn', 'value'=>'tn'),
		'to' => array('label'=>'Tonga', 'data-imagecss'=>'flag to', 'value'=>'to'),
		'tp' => array('label'=>'East Timor', 'data-imagecss'=>'flag tp', 'value'=>'tp'),
		'tr' => array('label'=>'Turkey', 'data-imagecss'=>'flag tr', 'value'=>'tr'),
		'tt' => array('label'=>'Trinidad and Tobago', 'data-imagecss'=>'flag tt', 'value'=>'tt'),
		'tv' => array('label'=>'Tuvalu', 'data-imagecss'=>'flag tv', 'value'=>'tv'),
		'tw' => array('label'=>'Taiwan', 'data-imagecss'=>'flag tw', 'value'=>'tw'),
		'tz' => array('label'=>'Tanzania', 'data-imagecss'=>'flag tz', 'value'=>'tz'),
		'ua' => array('label'=>'Ukraine', 'data-imagecss'=>'flag ua', 'value'=>'ua'),
		'ug' => array('label'=>'Uganda', 'data-imagecss'=>'flag ug', 'value'=>'ug'),
		'uk' => array('label'=>'United Kingdom', 'data-imagecss'=>'flag uk', 'value'=>'uk'),
		'um' => array('label'=>'United States Minor Outlying Islands', 'data-imagecss'=>'flag um', 'value'=>'um'),
		'us' => array('label'=>'United States', 'data-imagecss'=>'flag us', 'value'=>'us'),
		'uy' => array('label'=>'Uruguay', 'data-imagecss'=>'flag uy', 'value'=>'uy'),
		'uz' => array('label'=>'Uzbekistan', 'data-imagecss'=>'flag uz', 'value'=>'uz'),
		'va' => array('label'=>'Vatican City State (Holy See)', 'data-imagecss'=>'flag va', 'value'=>'va'),
		'vc' => array('label'=>'Saint Vincent and the Grenadines', 'data-imagecss'=>'flag vc', 'value'=>'vc'),
		've' => array('label'=>'Venezuela', 'data-imagecss'=>'flag ve', 'value'=>'ve'),
		'vg' => array('label'=>'Virgin Islands (British)', 'data-imagecss'=>'flag vg', 'value'=>'vg'),
		'vi' => array('label'=>'Virgin Islands (U.S.)', 'data-imagecss'=>'flag vi', 'value'=>'vi'),
		'vn' => array('label'=>'Viet Nam', 'data-imagecss'=>'flag vn', 'value'=>'vn'),
		'vu' => array('label'=>'Vanuatu', 'data-imagecss'=>'flag vu', 'value'=>'vu'),
		'wf' => array('label'=>'Wallis and Futuna', 'data-imagecss'=>'flag wf', 'value'=>'wf'),
		'ws' => array('label'=>'Samoa', 'data-imagecss'=>'flag ws', 'value'=>'ws'),
		'ye' => array('label'=>'Yemen', 'data-imagecss'=>'flag ye', 'value'=>'ye'),
		'yt' => array('label'=>'Mayotte', 'data-imagecss'=>'flag yt', 'value'=>'yt'),
		'yu' => array('label'=>'Yugoslavia (former)', 'data-imagecss'=>'flag yu', 'value'=>'yu'),
		'za' => array('label'=>'South Africa', 'data-imagecss'=>'flag za', 'value'=>'za'),
		'zm' => array('label'=>'Zambia', 'data-imagecss'=>'flag zm', 'value'=>'zm'),
		'zr' => array('label'=>'Zaire (former)', 'data-imagecss'=>'flag zr', 'value'=>'zr'),
		'zw' => array('label'=>'Zimbabwe', 'data-imagecss'=>'flag zw', 'value'=>'zw')
	);